<?php
echo '

<form action="https://91.208.121.201/estore_listener.php" name="uniteller" method="post">
		<input type="hidden" name="SHOP_ID" value="'.@$variables['purchase']['purchasing']['uni_id'].'" >
		<input type="hidden" name="LOGIN" value="'.@$variables['purchase']['purchasing']['uni_login'].'" >
		<input type="hidden" name="ORDER_ID" value="'.$variables['purchase']['purchasing']['order_id'].'">
		<input type="hidden" name="PAY_SUM" value="'.$variables['purchase']['purchasing']['amount'].'" >
		<input type="hidden" name="VALUE_1" value="'.$variables['purchase']['purchasing']['order_id'].'" >
		<input type="hidden" name="URL_OK" value="'.$variables['purchase']['purchasing']['urlok'].'" >
		<input type="hidden" name="URL_NO" value="'.$variables['purchase']['purchasing']['urlno'].'" >
		<input type="hidden" name="SIGN" value="'.$variables['purchase']['purchasing']['sign'].'" >
		<input type="hidden" name="LANG" value="RU" >
	  </form>
	     
</form>
<p>
   <INPUT TYPE="button" value="Оплатить Visa" onclick="document.location = \''.$variables['purchase']['purchasing']['twpg_url'].'\'"> '.@$variables['purchase']['purchasing']['uni_submit'].'
	</p>
';
?>